include:
- project: 'subugoe/argo-cd-workflow'
  file: 
    # trigger downstream cross-project pipeline to update the helm chart; triggered on pushing a new tag
    - 'ci-templates/trigger-downstream-pipeline.yml'

variables:
  imageTag: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  harborPath: "sub-fe/digis"
  dest: "harbor.gwdg.de/${harborPath}/${CI_PROJECT_NAME}:${imageTag}"

# Override variables and rules for included trigger job
trigger-downstream-pipeline:
  variables:
    IMAGE_TAG: ${imageTag}
    REPOSITORY_PATH: fe/digis/websearch_helm
  rules:
  - if: $CI_COMMIT_BRANCH == "develop"


.kaniko_template: &kaniko
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    # add docker credentials
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"harbor.gwdg.de\":{\"auth\":\"$(printf "%s:%s" "robot\$sub-fe+sub-fe-digis" "${DIGIS_HARBOR_ROBOT_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
 script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}" 
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg vcs_ref=${CI_COMMIT_SHORT_SHA}
      --destination ${dest}

build_image_dev:
  <<: *kaniko
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

# TODO: Find workflow for prod 
#build_liveimage:
#  <<: *kaniko
#  # we just add the “live” tag here…
#  script:
#    - /kaniko/executor
#      --context .
#      --dockerfile ./Dockerfile
#      --build-arg build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
#      --build-arg vcs_ref=${CI_COMMIT_SHORT_SHA}
#      --destination ${IMAGE_TAG}
#      --destination $CI_REGISTRY:live
#  rules:
#    - if: $CI_COMMIT_TAG
#